bank/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter
from .api import TransactionView
from .views import ExternalTransfer
from . import views

app_name = "bank"

router = SimpleRouter()
# router.register('transactions', views.TransactionView, basename='transactions')


urlpatterns = [
    path('', views.index, name='index'),

    path('dashboard/', views.dashboard, name='dashboard'),
    path('account_details/<int:pk>/',
         views.account_details, name='account_details'),
    path('transaction_details/<int:transaction>/',
         views.transaction_details, name='transaction_details'),

    path('make_transfer/', views.make_transfer, name='make_transfer'),
    path('make_loan/', views.make_loan, name='make_loan'),
    path('external_transfer/', ExternalTransfer.as_view(),
         name='external_transfer'),
    path('api/v1/transactions/',
         TransactionView.as_view(), name='transactions'),

    path('staff_dashboard/', views.staff_dashboard, name='staff_dashboard'),
    path('staff_search_partial/', views.staff_search_partial,
         name='staff_search_partial'),
    path('staff_customer_details/<int:pk>/',
         views.staff_customer_details, name='staff_customer_details'),
    path('staff_account_list_partial/<int:pk>/',
         views.staff_account_list_partial, name='staff_account_list_partial'),
    path('staff_account_details/<int:pk>/',
         views.staff_account_details, name='staff_account_details'),
    path('staff_new_account_partial/<int:user>/',
         views.staff_new_account_partial, name='staff_new_account_partial'),
    path('staff_new_customer/', views.staff_new_customer,
         name='staff_new_customer'),
    path('account_details/<int:pk>/bank_report/',
         views.create_pdf_report, name='bank_report')
]

taco_bank/urls.py
from django.contrib import admin
from django.urls import path, include
from two_factor.urls import urlpatterns as tf_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(tf_urls)),
    path('account/', include('django.contrib.auth.urls')),
    path('', include('bank.urls')),
    path('docs/', include('docs.urls')),
]

bank/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.core.validators import RegexValidator

from .models import Customer, Account


class TransferForm(forms.Form):
    amount = forms.DecimalField(label='Amount', max_digits=10)
    debit_account = forms.ModelChoiceField(
        label='Debit Account', queryset=Customer.objects.none())
    debit_text = forms.CharField(label='Debit Account Text', max_length=25)
    credit_account = forms.IntegerField(label='Credit Account Number')
    credit_text = forms.CharField(label='Credit Account Text', max_length=25)

    def clean(self):
        super().clean()

        # Ensure credit account exist
        credit_account = self.cleaned_data.get('credit_account')
        try:
            Account.objects.get(pk=credit_account)
        except ObjectDoesNotExist:
            self._errors['credit_account'] = self.error_class(
                ['Credit account does not exist.'])

        # Ensure positive amount
        if self.cleaned_data.get('amount') < 0:
            self._errors['amount'] = self.error_class(
                ['Amount must be positive.'])

        return self.cleaned_data


class ExternalTransferForm(forms.Form):
    amount = forms.DecimalField(label='Amount', max_digits=10)
    # To
    credit_account_number = forms.IntegerField(label='Credit Account Number')
    receiver_username = forms.CharField(label="Receiver's username")
    bank_registered_number = forms.IntegerField(
        label="Bank's registered number", validators=[RegexValidator(r'\d{4,4}', 'Number must be 4 digits', 'Invalid number')])
    credit_account = f'{credit_account_number} :: {receiver_username} :: {bank_registered_number}'
    credit_text = forms.CharField(label='Note to receiver', max_length=25)
    # From
    debit_account = forms.ModelChoiceField(
        label='Debit Account', queryset=Customer.objects.none())
    debit_text = forms.CharField(
        label='Note', max_length=25)

    def clean(self):
        super().clean()

        # Amount cannot be negative
        if self.cleaned_data.get('amount') < 0:
            self._errors['amount'] = self.error_class(
                ['Amount must be positive.'])

        return self.cleaned_data


class NewUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def clean(self):
        super().clean()
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username):
            self._errors['username'] = self.error_class(
                ['Username already exists.'])
        return self.cleaned_data


class UserForm(forms.ModelForm):
    username = forms.CharField(label='Username', disabled=True)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('rank', 'personal_id', 'phone')


class NewAccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('name',)

bank/views.py
from decimal import Decimal
from secrets import token_urlsafe
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, reverse, get_object_or_404
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.db import IntegrityError
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework import status
import requests

from .forms import TransferForm, ExternalTransferForm, UserForm, CustomerForm, NewUserForm, NewAccountForm
from .models import Account, Ledger, Customer, Transaction
from .serializers import TransactionsSerializer
from .errors import InsufficientFunds
from .utils import search_reg_number

from xhtml2pdf import pisa
from django.template.loader import get_template


def index(request):
    if request.user.is_staff:
        return HttpResponseRedirect(reverse('bank:staff_dashboard'))
    else:
        return HttpResponseRedirect(reverse('bank:dashboard'))


# Customer views

def dashboard(request):
    assert not request.user.is_staff, 'Staff user routing customer view.'

    accounts = request.user.customer.accounts
    context = {
        'accounts': accounts,
    }
    return render(request, 'bank/dashboard.html', context)


def account_details(request, pk):
    assert not request.user.is_staff, 'Staff user routing customer view.'

    account = get_object_or_404(Account, user=request.user, pk=pk)
    context = {
        'account': account,
    }
    return render(request, 'bank/account_details.html', context)


def transaction_details(request, transaction):
    movements = Ledger.objects.filter(transaction=transaction)
    if not request.user.is_staff:
        if not movements.filter(account__in=request.user.customer.accounts):
            raise PermissionDenied('Customer is not part of the transaction.')

    context = {
        'movements': movements,
    }
    return render(request, 'bank/transaction_details.html', context)


def make_transfer(request):
    assert not request.user.is_staff, 'Staff user routing customer view.'

    if request.method == 'POST':
        form = TransferForm(request.POST)
        form.fields['debit_account'].queryset = request.user.customer.accounts
        if form.is_valid():
            amount = form.cleaned_data['amount']
            debit_account = Account.objects.get(
                pk=form.cleaned_data['debit_account'].pk)
            debit_text = form.cleaned_data['debit_text']
            credit_account = Account.objects.get(
                pk=form.cleaned_data['credit_account'])
            credit_text = form.cleaned_data['credit_text']
            try:
                transfer = Ledger.transfer(
                    amount, debit_account, debit_text, credit_account, credit_text)
                return transaction_details(request, transfer)
            except InsufficientFunds:
                context = {
                    'title': 'Transfer Error',
                    'error': 'Insufficient funds for transfer.'
                }
                return render(request, 'bank/error.html', context)
    else:
        form = TransferForm()
    form.fields['debit_account'].queryset = request.user.customer.accounts
    context = {
        'form': form,
    }
    return render(request, 'bank/make_transfer.html', context)


class ExternalTransfer(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "bank/external_transfer.html"

    def get(self, request, format=None):
        assert not request.user.is_staff
        form = ExternalTransferForm()
        form.fields['debit_account'].queryset = request.user.customer.accounts
        return Response({'form': form}, status=status.HTTP_200_OK)

    def post(self, request):
        form = ExternalTransferForm(request.POST)
        form.fields['debit_account'].queryset = request.user.customer.accounts

        if form.is_valid():
            # Add the necessary fields for external transfer
            amount = form.cleaned_data['amount']
            # To
            credit_account_number = form.cleaned_data['credit_account_number']
            receiver_username = form.cleaned_data['receiver_username']
            bank_registered_number = form.cleaned_data['bank_registered_number']
            credit_account = f'{credit_account_number} :: {receiver_username} :: {bank_registered_number}'
            credit_text = form.cleaned_data['credit_text']
            # From
            debit_account = Account.objects.get(
                pk=form.cleaned_data['debit_account'].pk)
            debit_text = form.cleaned_data['debit_text']
            try:
                # Register this transaction in Ledger table
                transfer = Ledger.external_transfer(
                    amount, debit_account, debit_text, credit_account, credit_text)
                # Register this transaction to Transaction table
                transaction_data = request.data
                transaction_serializer = TransactionsSerializer(
                    data=transaction_data)
                if not transaction_serializer.is_valid():
                    return Response(transaction_serializer.errors, status=status.HTTP_400_BAD_REQUEST)

                transaction_serializer.save(
                    transaction=transfer.id, debit_account=debit_account, credit_account=credit_account, text=debit_text, )

                # Also send this to another bank, according to instance's port number
                data = {
                    "amount": amount,
                    "transaction": transfer.id,
                    "debit_account":  debit_account,
                    "credit_account": credit_account,
                    "text": debit_text,
                }

                port_to_send = search_reg_number(bank_registered_number)
                url = f'http://127.0.0.1:{port_to_send}/api/v1/transactions/'
                r = requests.post(url, data=data)
                r.raise_for_status()
                # print('sent to another bank', r.status_code)

                return transaction_details(request, transfer)
            except InsufficientFunds:
                context = {'title': 'Transfer Error',
                           'error': 'Insufficient funds for transfer.'}
                return render(request, 'bank/error.html', context)

        return Response({'form': form}, status=status.HTTP_200_OK)


def make_loan(request):
    assert not request.user.is_staff, 'Staff user routing customer view.'

    if request.user.customer.can_make_loan == 'B':
        context = {'title': 'Create Loan Error',
                   'error': 'Loan could not be completed. Loan can not be offered to Basic rank.'}
        return render(request, 'bank/error.html', context)

    if request.method == 'POST':
        request.user.customer.make_loan(Decimal(
            request.POST['amount']), request.POST['name'], request.POST['payment_period'])
        return HttpResponseRedirect(reverse('bank:dashboard'))
    return render(request, 'bank/make_loan.html', {})


# Staff views
def staff_dashboard(request):
    assert request.user.is_staff, 'Customer user routing staff view.'
    transactions = Transaction.objects.all()

    context = {
        'transactions': transactions,
    }

    return render(request, 'bank/staff_dashboard.html', context)


def staff_search_partial(request):
    assert request.user.is_staff, 'Customer user routing staff view.'

    search_term = request.POST['search_term']
    customers = Customer.search(search_term)
    context = {
        'customers': customers,
    }
    return render(request, 'bank/staff_search_partial.html', context)


def staff_customer_details(request, pk):
    assert request.user.is_staff, 'Customer user routing staff view.'

    customer = get_object_or_404(Customer, pk=pk)
    if request.method == 'GET':
        user_form = UserForm(instance=customer.user)
        customer_form = CustomerForm(instance=customer)
    elif request.method == 'POST':
        user_form = UserForm(request.POST, instance=customer.user)
        customer_form = CustomerForm(request.POST, instance=customer)
        if user_form.is_valid() and customer_form.is_valid():
            user_form.save()
            customer_form.save()
    new_account_form = NewAccountForm()
    context = {
        'customer': customer,
        'user_form': user_form,
        'customer_form': customer_form,
        'new_account_form': new_account_form,
    }
    return render(request, 'bank/staff_customer_details.html', context)


def staff_account_list_partial(request, pk):
    assert request.user.is_staff, 'Customer user routing staff view.'

    customer = get_object_or_404(Customer, pk=pk)
    accounts = customer.accounts
    context = {
        'accounts': accounts,
    }
    return render(request, 'bank/staff_account_list_partial.html', context)


def staff_account_details(request, pk):
    assert request.user.is_staff, 'Customer user routing staff view.'

    account = get_object_or_404(Account, pk=pk)
    context = {
        'account': account,
    }
    return render(request, 'bank/account_details.html', context)


def staff_new_account_partial(request, user):
    assert request.user.is_staff, 'Customer user routing staff view.'

    if request.method == 'POST':
        new_account_form = NewAccountForm(request.POST)
        current_user = User.objects.get(pk=user)
        all_accounts = Account.objects.filter(user=user)

        if new_account_form.is_valid():
            if all_accounts.count() == 0:
                Account.objects.create(user=current_user, name="Nemkonto")
            else:
                Account.objects.create(
                    user=current_user, name=new_account_form.cleaned_data['name'])
    return HttpResponseRedirect(reverse('bank:staff_customer_details', args=(user,)))


def staff_new_customer(request):

bank/templates/bank/account_details.html
{% extends "base.html" %}

{% block content_wrapper %}

{% if user.is_staff %}
<p>Welcome, {{ user }}.</p>
{% else %}
<p>Welcome, {{ user.customer.full_name }}.</p>
{% endif %}

<h3>Account Details</h3>

<table>
    <tr>
        <th>Account Number</th>
        <th>Account Name</th>
        <th>Balance</th>
        <th>Bank Report<th>
    </tr>
    <tr>
        <td>{{ account.id }}</td>
        <td>{{ account.name }}</td>
        <td class="amount">{{ account.balance|floatformat:"2" }}</td>
        <td style="text-align:right"><a href="{% url 'bank:bank_report' account.pk %}">Download</a></td>
    </tr>
</table>

<h3>Account Transactions</h3>
<table>
    <tr>
        <th>Transaction UID</th>
        <th>Amount</th>
        <th>Date and Time</th>
        <th>Text</th>
    </tr>
    {% for movement in account.movements %}
    <tr>
        <td><a href="{% url 'bank:transaction_details' movement.transaction %}">{{ movement.transaction }}</a></td>
        <td>{{ movement.amount|floatformat:"2" }}</td>
        <td>{{ movement.timestamp }}</td>
        <td>{{ movement.text }}</td>
    </tr>
    {% endfor %}
</table>

{% endblock content_wrapper %}

bank/templates/bank/bank_statement.html
{% extends "base_minimal.html" %}
{% block content_wrapper %}

<div style="text-align:right">
    <p>{{ user.customer.full_name }}</p>
    <p style="font-weight: bold"> Account ID: <span> {{account.pk}} </span></p>
    <p style="font-weight: bold"> Account Name: <span>{{account.name}}</span><p>
    <p style="font-weight: bold"> Balance: <span class="amount">{{ account.balance|floatformat:"2" }}</span></p>
</div>
<h3 style="margin-top: 50px">Account Transactions</h3>
<table>
    <tr>
        <th>Transaction UID</th>
        <th>Amount</th>
        <th>Date and Time</th>
        <th>Text</th>
    </tr>
    {% for movement in account.movements %}
    <tr>
        <td style="text-align:center">{{ movement.transaction }}</td>
        <td style="text-align:center">{{ movement.amount|floatformat:"2" }}</td>
        <td style="text-align:center">{{ movement.timestamp }}</td>
        <td style="text-align:center">{{ movement.text }}</td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

bank/templates/bank/dashboard.html
{% extends "base.html" %}

{% block content_wrapper %}

<p>Welcome, {{ user.customer.full_name }}.</p>

<h3>My accounts:</h3>
<table>
    <tr>
        <th>Account Number</th>
        <th>Account Name</th>
    </tr>
    {% for account in accounts %}
    <tr>
        <td><a href="{% url 'bank:account_details' account.pk %}">{{ account.pk }}</a></td>
        <td>{{ account.name }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock content_wrapper %}

bank/templates/bank/error.html
{% extends "base.html" %}

{% block content_wrapper %}

<p>Welcome, {% if user.is_staff %}{{ user.username }}{% else %}{{ user.customer.full_name }}{% endif %}.</p>

<h3>{{ title }}</h3>

<p>{{ error }}</p>

{% endblock %}

bank/templates/bank/external_transfer.html
{% extends "base.html" %} {% block content_wrapper %}
<form action="{% url 'bank:external_transfer' %}" method="post">
	{% csrf_token %}
	<fieldset>
	{{ form }}
	</fieldset>
	<br />
	<button type="submit">Submit external transfer</button>
</form>
{% endblock content_wrapper %}

bank/templates/bank/make_loan.html
{% extends "base.html" %}

{% block content_wrapper %}
<form action="{% url 'bank:make_loan' %}" method="post">
    {% csrf_token %}
    <fieldset>
    <label>
        Name for loan
        <input name="name" type="text" />
    </label>
    <label>
        Amount
        <input name="amount" />
    </label>
    <label>
        Payment type
        <select name="payment_period">
            <option value"3"> 3 months </option>
            <option value="6" selected="selected"> 6 months </option>
            <option value="9"> 9 months </option>
            <option value="12"> 12 months </option>
            <option value="15"> 15 months </option>
        </select>
    </label>
    <button>Submit</button>
    </fieldset>
</form>
{% endblock %}

bank/templates/bank/make_transfer.html
{% extends "base.html" %} {% block content_wrapper %}
<form action="{% url 'bank:make_transfer' %}" method="post">
	{% csrf_token %}
	<fieldset>
		{{ form }}
		<br />
		<button>Transfer</button>
	</fieldset>
</form>
{% endblock %}

bank/templates/bank/staff_account_list_partial.html
<tbody id="account-list">
{% for account in accounts %}
    <tr>
        <td><a href="{% url 'bank:staff_account_details' account.pk %}">{{ account.pk }}</a></td>
        <td>{{ account.name }}</td>
        <td>{{ account.balance|floatformat:"2" }}</td>
    </tr>
{% endfor %}
</tbody>

bank/templates/bank/staff_customer_details.html
{% extends "base.html" %}

{% block content_wrapper %}

<h3>Customer Details</h3>

<form action="{% url 'bank:staff_customer_details' customer.pk %}" method="post">
    {% csrf_token %}
    <fieldset>
        {{ user_form.as_p }}
        {{ customer_form.as_p }}
    <button>Update User</button>
    </fieldset>
</form>

<table>
    <thead>
        <tr>
            <th>Account Number</th>
            <th>Account Name</th>
            <th>Account Balance</th>
        </tr>
    </thead>
    <tbody
        id="account-list"
        hx-swap="outerHTML"
        hx-get="{% url 'bank:staff_account_list_partial' customer.pk %}"
        hx-trigger="load">
    </tbody>
</table>

<h3>Create New Account</h3>
<form action="{% url 'bank:staff_new_account_partial' customer.user.pk %}" method="post">
    {% csrf_token %}
    <fieldset>
        {{ new_account_form.as_p }}
    <button>Create Account</button>
    </fieldset>
</form>

{% endblock %}

bank/templates/bank/staff_dashboard.html
{% extends "base.html" %} {% block content_wrapper %}

<p>Welcome, {{ user }}.</p>

<fieldset>
	<label>Customer Look Up</label>
	<input
		name="search_term"
		placeholder="Search on customer data"
		class="form-control"
		type="text"
		hx-post="{% url 'bank:staff_search_partial' %}"
		hx-trigger="keyup changed delay:500ms"
		hx-target="#search-results"
		hx-indicator=".htmx-indicator"
	/>
	{% csrf_token %}
</fieldset>

<table>
    <thead>
        <th>ID</th>
        <th>Personal ID</th>
        <th>Name</th>
        <th>Phone</th>
        <th>Email</th>
        <th>Accounts</th>
    </thead>
    <tbody id="search-results">
    </tbody>
</table>

<br />
<h3>Transactions</h3>
<table>
	<thead>
		<th>Transaction UID</th>
		<th>Amount</th>
		<th>From</th>
		<th>To</th>
		<th>Text</th>
		<th>Created on</th>
	</thead>
	<tbody>
		{% for transaction in transactions %}
		<tr>
			<td>{{ transaction.transaction }}</td>
			<td>{{ transaction.amount }}</td>
			<td>{{ transaction.debit_account }}</td>
			<td>{{ transaction.credit_account }}</td>
			<td>{{ transaction.debit_text}}</td>
			<td>{{ transaction.timestamp}}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% endblock content_wrapper %}

bank/templates/bank/staff_new_customer.html
{% extends "base.html" %}

{% block content_wrapper %}
<form action="{% url 'bank:staff_new_customer' %}" method="post">
    {% csrf_token %}
    <fieldset>
        {{ new_user_form }}
        {{ customer_form }}
    <button>Create User</button>
    </fieldset>
</form>
{% endblock %}

bank/templates/bank/staff_search_partial.html
{% for customer in customers %}
<tr>
    <td><a href="{% url 'bank:staff_customer_details' customer.pk %}">{{ customer.pk }}</a></td>
    <td>{{ customer.personal_id }}</td>
    <td>{{ customer.full_name }}</td>
    <td>{{ customer.phone }}</td>
    <td>{{ customer.user.email }}</td>
    <td><a href="{% url 'bank:staff_customer_details' customer.pk %}">View</a></td>
</tr>
{% endfor %}

bank/templates/bank/transaction_details.html
{% extends "base.html" %} {% block content_wrapper %}

<p>Welcome, {{ user.customer.full_name }}.</p>

<h3>Transaction Details</h3>

<table>
	<tr>
		<th>Account Number</th>
		<th>Transaction UID</th>
		<th>Amount</th>
		<th>Date and Time</th>
		<th>Text</th>
	</tr>
	{% for movement in movements %}
	<tr>
		{% if movement.account != None and movement.external_credit_account == 'Not external' and  movement.external_debit_account == 'Not external' %}
		<td>{{ movement.account }} </td>
      {% endif %}

		{% if movement.external_credit_account == 'Not external' and movement.account == None %}
      <td>{{ movement.external_debit_account }}</td>
      {% endif %}

		{% if movement.external_debit_account == 'Not external' and movement.account == None %}
      <td>{{ movement.external_credit_account }}</td>
      {% endif %}

		<td>{{ movement.transaction }}</td>
		<td>{{ movement.amount|floatformat:"2" }}</td>
		<td>{{ movement.timestamp }}</td>
		<td>{{ movement.text }}</td>
	</tr>
	{% endfor %}
</table>

{% endblock %}